export const level_1 = [
  "United States of America",
  "Mexico",
  "Canada",
  "Argentina",
  "Brazil",
  "India",
  "China",
  "South Korea",
  "North Korea",
  "Japan",
  "South Africa",
  "Madagascar",
  "France",
  "Russia",
  "Germany",
  "Spain",
  "Italy",
  "United Kingdom",
  "Australia",
  "New Zealand",
];

export const level_2 = [
  "Egypt",
  "Chile",
  "Greenland",
  "The Bahamas",
  "Iceland",
  "Portugal",
  "Poland",
  "Ireland",
  "Greece",
  "Sweden",
  "Norway",
  "Finland",
  "Puerto Rico",
  "Jamaica",
  "Cuba",
  "Philippines",
  "Sri Lanka",
  "Taiwan",
  "Ethiopia",
  "Ukraine",
  "Uganda",
  "Zimbabwe",
  "Nigeria",
  "Sudan",
  "Morocco",
  "Kenya",
  "Iraq",
  "Pakistan",
  "Iran",
  "Saudi Arabia",
  "Thailand",
  "Cambodia",
  "Vietnam",
  "Israel",
  "Palestine",
  "Lebanon",
  "Costa Rica",
  "Nicaragua",
  "Guatemala",
  "Venezuela",
];

export const level_3 = [
  "Qatar",
  "Colombia",
  "Ecuador",
  "Yemen",
  "Nepal",
  "Myanmar",
  "Bangladesh",
  "Afghanistan",
  "Jordan",
  "Kuwait",
  "Turkey",
  "United Arab Emirates",
  "Mongolia",
  "Laos",
  "Malaysia",
  "Syria",
  "Indonesia",
  "El Salvador",
  "Haiti",
  "Dominican Republic",
  "Honduras",
  "Belize",
  "Panama",
  "Trinidad and Tobago",
  "Bolivia",
  "Peru",
  "Suriname",
  "Guyana",
  "Uruguay",
  "Paraguay",
  "Chad",
  "Niger",
  "Belarus",
  "Lithuania",
  "Czechia",
  "Estonia",
  "Latvia",
  "Luxembourg",
  "Belgium",
  "Albania",
  "North Macedonia",
  "Denmark",
  "Romania",
  "Hungary",
  "Slovakia",
  "Austria",
  "Netherlands",
  "Switzerland",
  "Papua New Guinea",
  "Fiji",
];

export const level_4 = [
  "Falkland Islands",
  "Cyprus",
  "Bhutan",
  "Uzbekistan",
  "Kazakhstan",
  "Tajikistan",
  "Azerbaijan",
  "East Timor",
  "Brunei",
  "Turkmenistan",
  "Namibia",
  "Zambia",
  "Sierra Leone",
  "Liberia",
  "Guinea",
  "Central African Republic",
  "Djibouti",
  "Eritrea",
  "Burkina Faso",
  "Guinea-Bissau",
  "Togo",
  "Ghana",
  "Mauritania",
  "Equatorial Guinea",
  "Gambia",
  "Oman",
  "Georgia",
  "Kyrgyzstan",
  "Armenia",
  "Northern Cyprus",
  "Malawi",
  "Benin",
  "Republic of Serbia",
  "Croatia",
  "Slovenia",
  "Bulgaria",
  "Montenegro",
  "Bosnia and Herzegovina",
  "Moldova",
  "New Caledonia",
  "Solomon Islands",
  "Vanuatu",
  "South Sudan",
  "Somalia",
  "United Republic of Tanzania",
  "Somaliland",
  "Western Sahara",
  "Republic of the Congo",
  "Democratic Republic of the Congo",
  "Tunisia",
  "Libya",
  "Ivory Coast",
  "Senegal",
  "Mali",
  "Angola",
  "Botswana",
  "Algeria",
  "Mozambique",
  "eSwatini",
  "Burundi",
  "Rwanda",
  "Cameroon",
  "Lesotho",
  "Gabon",
  "Kosovo",
];

export const level_5 = [
  "Costa Rica",
  "Nicaragua",
  "Guatemala",
  "El Salvador",
  "Cuba",
  "Haiti",
  "Dominican Republic",
  "Honduras",
  "United States of America",
  "Mexico",
  "Canada",
  "Belize",
  "Panama",
  "Greenland",
  "The Bahamas",
  "Trinidad and Tobago",
  "Puerto Rico",
  "Jamaica",
  "Chile",
  "Bolivia",
  "Peru",
  "Argentina",
  "Suriname",
  "Guyana",
  "Brazil",
  "Uruguay",
  "Colombia",
  "Ecuador",
  "Venezuela",
  "Paraguay",
  "Falkland Islands",
  "Indonesia",
  "Cyprus",
  "Malaysia",
  "India",
  "China",
  "Israel",
  "Palestine",
  "South Korea",
  "Lebanon",
  "Syria",
  "North Korea",
  "Bhutan",
  "Oman",
  "Uzbekistan",
  "Kazakhstan",
  "Tajikistan",
  "Mongolia",
  "Laos",
  "Azerbaijan",
  "Georgia",
  "Turkey",
  "Cambodia",
  "Vietnam",
  "United Arab Emirates",
  "Kyrgyzstan",
  "Armenia",
  "Iraq",
  "Pakistan",
  "Qatar",
  "Iran",
  "Saudi Arabia",
  "Thailand",
  "Kuwait",
  "East Timor",
  "Brunei",
  "Myanmar",
  "Bangladesh",
  "Afghanistan",
  "Jordan",
  "Turkmenistan",
  "Nepal",
  "Northern Cyprus",
  "Yemen",
  "Philippines",
  "Sri Lanka",
  "Taiwan",
  "Japan",
  "Ethiopia",
  "South Sudan",
  "Somalia",
  "Kenya",
  "Malawi",
  "United Republic of Tanzania",
  "Somaliland",
  "Western Sahara",
  "Morocco",
  "Republic of the Congo",
  "Democratic Republic of the Congo",
  "Tunisia",
  "South Africa",
  "Libya",
  "Namibia",
  "Zambia",
  "Sierra Leone",
  "Liberia",
  "Guinea",
  "Central African Republic",
  "Sudan",
  "Djibouti",
  "Eritrea",
  "Ivory Coast",
  "Senegal",
  "Mali",
  "Benin",
  "Nigeria",
  "Angola",
  "Botswana",
  "Zimbabwe",
  "Algeria",
  "Mozambique",
  "Chad",
  "eSwatini",
  "Burundi",
  "Rwanda",
  "Uganda",
  "Cameroon",
  "Lesotho",
  "Gabon",
  "Niger",
  "Burkina Faso",
  "Guinea-Bissau",
  "Togo",
  "Ghana",
  "Egypt",
  "Mauritania",
  "Equatorial Guinea",
  "Gambia",
  "Madagascar",
  "France",
  "Ukraine",
  "Belarus",
  "Lithuania",
  "Russia",
  "Czechia",
  "Estonia",
  "Latvia",
  "Germany",
  "Sweden",
  "Norway",
  "Finland",
  "Luxembourg",
  "Belgium",
  "Albania",
  "North Macedonia",
  "Kosovo",
  "Denmark",
  "Spain",
  "Romania",
  "Hungary",
  "Slovakia",
  "Poland",
  "Ireland",
  "United Kingdom",
  "Greece",
  "Italy",
  "Austria",
  "Netherlands",
  "Switzerland",
  "Republic of Serbia",
  "Croatia",
  "Slovenia",
  "Bulgaria",
  "Montenegro",
  "Bosnia and Herzegovina",
  "Portugal",
  "Moldova",
  "Iceland",
  "Papua New Guinea",
  "Australia",
  "Fiji",
  "New Zealand",
  "New Caledonia",
  "Solomon Islands",
  "Vanuatu",
];

export default {
  level_1,
  level_2,
  level_3,
  level_4,
  level_5,
};
